GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "laetitia29@gmail.com",
    "resident": "Carole"
  }

###
GET http://localhost:3000/resident

###
POST http://localhost:3000/resident
Content-Type: application/json

{
    "prénom": "Carole"
  }

###
GET http://localhost:3000/post


###
POST http://localhost:3000/post
Content-Type: application/json

{
    "titre": "Photo de Vincent!",
    "resident": "Vincent",
    "photo":"https://www.bing.com/th?id=OIP.Vq-2In1vPclSQD3kYBqu0gHaHa&w=201&h=185&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2"
  }